server {
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name INSERT_DOMAIN_NAME_HERE;

	ssl_certificate_key INSERT_KEY_PATH_HERE;
	ssl_certificate INSERT_CRT_PATH_HERE;
	ssl_protocols TLSv1.2 TLSv1.3;


	root /var/www/html;

	index index.php;

	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass wordpress:9000;
	}
}